[31m---------------------------------------------------------------------------[39m
[31mSSLCertVerificationError[39m                  Traceback (most recent call last)
[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/connector.py:1283[39m, in [36m_wrap_create_connection[39m[34m()[39m
[32m   1282[39m             kwargs[[33m"[39m[33mssl_shutdown_timeout[39m[33m"[39m] = [38;5;28mself[39m._ssl_shutdown_timeout
[32m-> [39m[32m1283[39m         [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m [38;5;28mself[39m._loop.create_connection(*args, **kwargs, sock=sock)
[32m   1284[39m [38;5;28;01mexcept[39;00m cert_errors [38;5;28;01mas[39;00m exc:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/asyncio/base_events.py:1159[39m, in [36mcreate_connection[39m[34m()[39m
[32m   1156[39m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[32m   1157[39m             [33mf[39m[33m'[39m[33mA Stream Socket was expected, got [39m[38;5;132;01m{[39;00msock[38;5;132;01m!r}[39;00m[33m'[39m)
[32m-> [39m[32m1159[39m transport, protocol = [38;5;28;01mawait[39;00m [38;5;28mself[39m._create_connection_transport(
[32m   1160[39m     sock, protocol_factory, ssl, server_hostname,
[32m   1161[39m     ssl_handshake_timeout=ssl_handshake_timeout,
[32m   1162[39m     ssl_shutdown_timeout=ssl_shutdown_timeout)
[32m   1163[39m [38;5;28;01mif[39;00m [38;5;28mself[39m._debug:
[32m   1164[39m     [38;5;66;03m# Get the socket from the transport because SSL transport closes[39;00m
[32m   1165[39m     [38;5;66;03m# the old socket and creates a new SSL socket[39;00m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/asyncio/base_events.py:1192[39m, in [36m_create_connection_transport[39m[34m()[39m
[32m   1191[39m [38;5;28;01mtry[39;00m:
[32m-> [39m[32m1192[39m     [38;5;28;01mawait[39;00m waiter
[32m   1193[39m [38;5;28;01mexcept[39;00m:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/asyncio/sslproto.py:581[39m, in [36m_on_handshake_complete[39m[34m()[39m
[32m    580[39m [38;5;28;01melse[39;00m:
[32m--> [39m[32m581[39m     [38;5;28;01mraise[39;00m handshake_exc
[32m    583[39m peercert = sslobj.getpeercert()

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/asyncio/sslproto.py:563[39m, in [36m_do_handshake[39m[34m()[39m
[32m    562[39m [38;5;28;01mtry[39;00m:
[32m--> [39m[32m563[39m     [38;5;28mself[39m._sslobj.do_handshake()
[32m    564[39m [38;5;28;01mexcept[39;00m SSLAgainErrors:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/ssl.py:916[39m, in [36mdo_handshake[39m[34m()[39m
[32m    915[39m [38;5;250m[39m[33;03m"""Start the SSL/TLS handshake."""[39;00m
[32m--> [39m[32m916[39m [38;5;28mself[39m._sslobj.do_handshake()

[31mSSLCertVerificationError[39m: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1010)

The above exception was the direct cause of the following exception:

[31mClientConnectorCertificateError[39m           Traceback (most recent call last)
[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/zarr/storage.py:1446[39m, in [36m__getitem__[39m[34m()[39m
[32m   1445[39m [38;5;28;01mtry[39;00m:
[32m-> [39m[32m1446[39m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m.map[key]
[32m   1447[39m [38;5;28;01mexcept[39;00m [38;5;28mself[39m.exceptions [38;5;28;01mas[39;00m e:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/fsspec/mapping.py:155[39m, in [36m__getitem__[39m[34m()[39m
[32m    154[39m [38;5;28;01mtry[39;00m:
[32m--> [39m[32m155[39m     result = [38;5;28mself[39m.fs.cat(k)
[32m    156[39m [38;5;28;01mexcept[39;00m [38;5;28mself[39m.missing_exceptions [38;5;28;01mas[39;00m exc:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/fsspec/asyn.py:118[39m, in [36mwrapper[39m[34m()[39m
[32m    117[39m [38;5;28mself[39m = obj [38;5;129;01mor[39;00m args[[32m0[39m]
[32m--> [39m[32m118[39m [38;5;28;01mreturn[39;00m sync([38;5;28mself[39m.loop, func, *args, **kwargs)

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/fsspec/asyn.py:103[39m, in [36msync[39m[34m()[39m
[32m    102[39m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(return_result, [38;5;167;01mBaseException[39;00m):
[32m--> [39m[32m103[39m     [38;5;28;01mraise[39;00m return_result
[32m    104[39m [38;5;28;01melse[39;00m:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/fsspec/asyn.py:56[39m, in [36m_runner[39m[34m()[39m
[32m     55[39m [38;5;28;01mtry[39;00m:
[32m---> [39m[32m56[39m     result[[32m0[39m] = [38;5;28;01mawait[39;00m coro
[32m     57[39m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m ex:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/fsspec/asyn.py:464[39m, in [36m_cat[39m[34m()[39m
[32m    463[39m     [38;5;28;01mif[39;00m ex:
[32m--> [39m[32m464[39m         [38;5;28;01mraise[39;00m ex
[32m    465[39m [38;5;28;01mif[39;00m (
[32m    466[39m     [38;5;28mlen[39m(paths) > [32m1[39m
[32m    467[39m     [38;5;129;01mor[39;00m [38;5;28misinstance[39m(path, [38;5;28mlist[39m)
[32m    468[39m     [38;5;129;01mor[39;00m paths[[32m0[39m] != [38;5;28mself[39m._strip_protocol(path)
[32m    469[39m ):

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/fsspec/asyn.py:244[39m, in [36m_run_coro[39m[34m()[39m
[32m    243[39m [38;5;28;01mtry[39;00m:
[32m--> [39m[32m244[39m     [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m asyncio.wait_for(coro, timeout=timeout), i
[32m    245[39m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/asyncio/tasks.py:520[39m, in [36mwait_for[39m[34m()[39m
[32m    519[39m [38;5;28;01masync[39;00m [38;5;28;01mwith[39;00m timeouts.timeout(timeout):
[32m--> [39m[32m520[39m     [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m fut

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/fsspec/implementations/http.py:244[39m, in [36m_cat_file[39m[34m()[39m
[32m    243[39m session = [38;5;28;01mawait[39;00m [38;5;28mself[39m.set_session()
[32m--> [39m[32m244[39m [38;5;28;01masync[39;00m [38;5;28;01mwith[39;00m session.get([38;5;28mself[39m.encode_url(url), **kw) [38;5;28;01mas[39;00m r:
[32m    245[39m     out = [38;5;28;01mawait[39;00m r.read()

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/client.py:1488[39m, in [36m__aenter__[39m[34m()[39m
[32m   1487[39m [38;5;28;01masync[39;00m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__aenter__[39m([38;5;28mself[39m) -> _RetType:
[32m-> [39m[32m1488[39m     [38;5;28mself[39m._resp: _RetType = [38;5;28;01mawait[39;00m [38;5;28mself[39m._coro
[32m   1489[39m     [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m [38;5;28mself[39m._resp.[34m__aenter__[39m()

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/client.py:770[39m, in [36m_request[39m[34m()[39m
[32m    769[39m [38;5;28;01mtry[39;00m:
[32m--> [39m[32m770[39m     resp = [38;5;28;01mawait[39;00m handler(req)
[32m    771[39m [38;5;66;03m# Client connector errors should not be retried[39;00m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/client.py:725[39m, in [36m_connect_and_send_request[39m[34m()[39m
[32m    724[39m [38;5;28;01mtry[39;00m:
[32m--> [39m[32m725[39m     conn = [38;5;28;01mawait[39;00m [38;5;28mself[39m._connector.connect(
[32m    726[39m         req, traces=traces, timeout=real_timeout
[32m    727[39m     )
[32m    728[39m [38;5;28;01mexcept[39;00m asyncio.TimeoutError [38;5;28;01mas[39;00m exc:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/connector.py:642[39m, in [36mconnect[39m[34m()[39m
[32m    641[39m         [38;5;28;01mawait[39;00m trace.send_connection_create_start()
[32m--> [39m[32m642[39m proto = [38;5;28;01mawait[39;00m [38;5;28mself[39m._create_connection(req, traces, timeout)
[32m    643[39m [38;5;28;01mif[39;00m traces:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/connector.py:1209[39m, in [36m_create_connection[39m[34m()[39m
[32m   1208[39m [38;5;28;01melse[39;00m:
[32m-> [39m[32m1209[39m     _, proto = [38;5;28;01mawait[39;00m [38;5;28mself[39m._create_direct_connection(req, traces, timeout)
[32m   1211[39m [38;5;28;01mreturn[39;00m proto

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/connector.py:1581[39m, in [36m_create_direct_connection[39m[34m()[39m
[32m   1580[39m [38;5;28;01massert[39;00m last_exc [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[32m-> [39m[32m1581[39m [38;5;28;01mraise[39;00m last_exc

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/connector.py:1550[39m, in [36m_create_direct_connection[39m[34m()[39m
[32m   1549[39m [38;5;28;01mtry[39;00m:
[32m-> [39m[32m1550[39m     transp, proto = [38;5;28;01mawait[39;00m [38;5;28mself[39m._wrap_create_connection(
[32m   1551[39m         [38;5;28mself[39m._factory,
[32m   1552[39m         timeout=timeout,
[32m   1553[39m         ssl=sslcontext,
[32m   1554[39m         addr_infos=addr_infos,
[32m   1555[39m         server_hostname=server_hostname,
[32m   1556[39m         req=req,
[32m   1557[39m         client_error=client_error,
[32m   1558[39m     )
[32m   1559[39m [38;5;28;01mexcept[39;00m (ClientConnectorError, asyncio.TimeoutError) [38;5;28;01mas[39;00m exc:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/aiohttp/connector.py:1285[39m, in [36m_wrap_create_connection[39m[34m()[39m
[32m   1284[39m [38;5;28;01mexcept[39;00m cert_errors [38;5;28;01mas[39;00m exc:
[32m-> [39m[32m1285[39m     [38;5;28;01mraise[39;00m ClientConnectorCertificateError(req.connection_key, exc) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mexc[39;00m
[32m   1286[39m [38;5;28;01mexcept[39;00m ssl_errors [38;5;28;01mas[39;00m exc:

[31mClientConnectorCertificateError[39m: Cannot connect to host osdf-data.gdex.ucar.edu:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1010)')]

The above exception was the direct cause of the following exception:

[31mKeyError[39m                                  Traceback (most recent call last)
[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/xarray/backends/zarr.py:1868[39m, in [36m_get_open_params[39m[34m()[39m
[32m   1867[39m [38;5;28;01mtry[39;00m:
[32m-> [39m[32m1868[39m     zarr_root_group = zarr.open_consolidated(store, **open_kwargs)
[32m   1869[39m [38;5;28;01mexcept[39;00m ([38;5;167;01mValueError[39;00m, [38;5;167;01mKeyError[39;00m):
[32m   1870[39m     [38;5;66;03m# ValueError in zarr-python 3.x, KeyError in 2.x.[39;00m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/zarr/convenience.py:1360[39m, in [36mopen_consolidated[39m[34m()[39m
[32m   1359[39m [38;5;66;03m# setup metadata store[39;00m
[32m-> [39m[32m1360[39m meta_store = ConsolidatedStoreClass(store, metadata_key=metadata_key)
[32m   1362[39m [38;5;66;03m# pass through[39;00m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/zarr/storage.py:3046[39m, in [36m__init__[39m[34m()[39m
[32m   3045[39m [38;5;66;03m# retrieve consolidated metadata[39;00m
[32m-> [39m[32m3046[39m meta = json_loads([38;5;28mself[39m.store[metadata_key])
[32m   3048[39m [38;5;66;03m# check format of consolidated metadata[39;00m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/zarr/storage.py:1448[39m, in [36m__getitem__[39m[34m()[39m
[32m   1447[39m [38;5;28;01mexcept[39;00m [38;5;28mself[39m.exceptions [38;5;28;01mas[39;00m e:
[32m-> [39m[32m1448[39m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01me[39;00m

[31mKeyError[39m: '.zmetadata'

During handling of the above exception, another exception occurred:

[31mGroupNotFoundError[39m                        Traceback (most recent call last)
[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/xarray/backends/zarr.py:1872[39m, in [36m_get_open_params[39m[34m()[39m
[32m   1871[39m [38;5;28;01mtry[39;00m:
[32m-> [39m[32m1872[39m     zarr_root_group = zarr.open_group(store, **open_kwargs)
[32m   1873[39m     emit_user_level_warning(
[32m   1874[39m         [33m"[39m[33mFailed to open Zarr store with consolidated metadata, [39m[33m"[39m
[32m   1875[39m         [33m"[39m[33mbut successfully read with non-consolidated metadata. [39m[33m"[39m
[32m   (...)[39m[32m   1885[39m         [38;5;167;01mRuntimeWarning[39;00m,
[32m   1886[39m     )

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/zarr/hierarchy.py:1578[39m, in [36mopen_group[39m[34m()[39m
[32m   1577[39m             [38;5;28;01mraise[39;00m ContainsArrayError(path)
[32m-> [39m[32m1578[39m         [38;5;28;01mraise[39;00m GroupNotFoundError(path)
[32m   1580[39m [38;5;28;01melif[39;00m mode == [33m"[39m[33mw[39m[33m"[39m:

[31mGroupNotFoundError[39m: group not found at path "group not found at path ''"

The above exception was the direct cause of the following exception:

[31mFileNotFoundError[39m                         Traceback (most recent call last)
[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake_esm/source.py:256[39m, in [36mESMDataSource._open_dataset[39m[34m(self)[39m
[32m    235[39m datasets = [
[32m    236[39m     _open_dataset(
[32m    237[39m         record[[38;5;28mself[39m.path_column_name],
[32m   (...)[39m[32m    253[39m     [38;5;28;01mfor[39;00m _, record [38;5;129;01min[39;00m [38;5;28mself[39m.df.iterrows()
[32m    254[39m ]
[32m--> [39m[32m256[39m datasets = [43mdask[49m[43m.[49m[43mcompute[49m[43m([49m[43m*[49m[43mdatasets[49m[43m)[49m
[32m    257[39m [38;5;28;01mif[39;00m [38;5;28mlen[39m(datasets) == [32m1[39m [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m datasets[[32m0[39m].data_vars:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/dask/base.py:681[39m, in [36mcompute[39m[34m(traverse, optimize_graph, scheduler, get, *args, **kwargs)[39m
[32m    679[39m     keys = [38;5;28mlist[39m(flatten(expr.__dask_keys__()))
[32m--> [39m[32m681[39m     results = [43mschedule[49m[43m([49m[43mexpr[49m[43m,[49m[43m [49m[43mkeys[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m
[32m    683[39m [38;5;28;01mreturn[39;00m repack(results)

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake_esm/source.py:82[39m, in [36m_open_dataset[39m[34m()[39m
[32m     81[39m [38;5;28;01melse[39;00m:
[32m---> [39m[32m82[39m     ds = xr.open_dataset(url, **xarray_open_kwargs)
[32m     83[39m     [38;5;28;01mif[39;00m preprocess [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/xarray/backends/api.py:596[39m, in [36mopen_dataset[39m[34m()[39m
[32m    595[39m overwrite_encoded_chunks = kwargs.pop([33m"[39m[33moverwrite_encoded_chunks[39m[33m"[39m, [38;5;28;01mNone[39;00m)
[32m--> [39m[32m596[39m backend_ds = backend.open_dataset(
[32m    597[39m     filename_or_obj,
[32m    598[39m     drop_variables=drop_variables,
[32m    599[39m     **decoders,
[32m    600[39m     **kwargs,
[32m    601[39m )
[32m    602[39m ds = _dataset_from_backend_dataset(
[32m    603[39m     backend_ds,
[32m    604[39m     filename_or_obj,
[32m   (...)[39m[32m    615[39m     **kwargs,
[32m    616[39m )

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/xarray/backends/zarr.py:1660[39m, in [36mopen_dataset[39m[34m()[39m
[32m   1659[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m store:
[32m-> [39m[32m1660[39m     store = ZarrStore.open_group(
[32m   1661[39m         filename_or_obj,
[32m   1662[39m         group=group,
[32m   1663[39m         mode=mode,
[32m   1664[39m         synchronizer=synchronizer,
[32m   1665[39m         consolidated=consolidated,
[32m   1666[39m         consolidate_on_close=[38;5;28;01mFalse[39;00m,
[32m   1667[39m         chunk_store=chunk_store,
[32m   1668[39m         storage_options=storage_options,
[32m   1669[39m         zarr_version=zarr_version,
[32m   1670[39m         use_zarr_fill_value_as_mask=[38;5;28;01mNone[39;00m,
[32m   1671[39m         zarr_format=zarr_format,
[32m   1672[39m         cache_members=cache_members,
[32m   1673[39m     )
[32m   1675[39m store_entrypoint = StoreBackendEntrypoint()

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/xarray/backends/zarr.py:714[39m, in [36mopen_group[39m[34m()[39m
[32m    688[39m [38;5;129m@classmethod[39m
[32m    689[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mopen_group[39m(
[32m    690[39m     [38;5;28mcls[39m,
[32m   (...)[39m[32m    707[39m     cache_members: [38;5;28mbool[39m = [38;5;28;01mTrue[39;00m,
[32m    708[39m ):
[32m    709[39m     (
[32m    710[39m         zarr_group,
[32m    711[39m         consolidate_on_close,
[32m    712[39m         close_store_on_close,
[32m    713[39m         use_zarr_fill_value_as_mask,
[32m--> [39m[32m714[39m     ) = _get_open_params(
[32m    715[39m         store=store,
[32m    716[39m         mode=mode,
[32m    717[39m         synchronizer=synchronizer,
[32m    718[39m         group=group,
[32m    719[39m         consolidated=consolidated,
[32m    720[39m         consolidate_on_close=consolidate_on_close,
[32m    721[39m         chunk_store=chunk_store,
[32m    722[39m         storage_options=storage_options,
[32m    723[39m         zarr_version=zarr_version,
[32m    724[39m         use_zarr_fill_value_as_mask=use_zarr_fill_value_as_mask,
[32m    725[39m         zarr_format=zarr_format,
[32m    726[39m     )
[32m    728[39m     [38;5;28;01mreturn[39;00m [38;5;28mcls[39m(
[32m    729[39m         zarr_group,
[32m    730[39m         mode,
[32m   (...)[39m[32m    739[39m         cache_members=cache_members,
[32m    740[39m     )

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/xarray/backends/zarr.py:1888[39m, in [36m_get_open_params[39m[34m()[39m
[32m   1887[39m         [38;5;28;01mexcept[39;00m missing_exc [38;5;28;01mas[39;00m err:
[32m-> [39m[32m1888[39m             [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m(
[32m   1889[39m                 [33mf[39m[33m"[39m[33mNo such file or directory: [39m[33m'[39m[38;5;132;01m{[39;00mstore[38;5;132;01m}[39;00m[33m'[39m[33m"[39m
[32m   1890[39m             ) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01merr[39;00m
[32m   1892[39m [38;5;66;03m# but the user should still receive a DataTree whose root is the group they asked for[39;00m

[31mFileNotFoundError[39m: No such file or directory: 'https://osdf-data.gdex.ucar.edu/ncar-gdex/d010092/ocn/monthly/cesm2LE-ssp370-smbb-TEMP.zarr'

The above exception was the direct cause of the following exception:

[31mESMDataSourceError[39m                        Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[9][39m[32m, line 1[39m
[32m----> [39m[32m1[39m dsets_cesm = [43mcesm_temp[49m[43m.[49m[43mto_dataset_dict[49m[43m([49m[43m)[49m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py:39[39m, in [36mupdate_wrapper_attributes.<locals>.wrapper_function[39m[34m(*args, **kwargs)[39m
[32m     37[39m [38;5;129m@functools[39m.wraps(wrapped)
[32m     38[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mwrapper_function[39m(*args, **kwargs):
[32m---> [39m[32m39[39m     [38;5;28;01mreturn[39;00m [43mwrapper[49m[43m([49m[43m*[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py:136[39m, in [36mValidateCallWrapper.__call__[39m[34m(self, *args, **kwargs)[39m
[32m    133[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m.__pydantic_complete__:
[32m    134[39m     [38;5;28mself[39m._create_validators()
[32m--> [39m[32m136[39m res = [38;5;28;43mself[39;49m[43m.[49m[43m__pydantic_validator__[49m[43m.[49m[43mvalidate_python[49m[43m([49m[43mpydantic_core[49m[43m.[49m[43mArgsKwargs[49m[43m([49m[43margs[49m[43m,[49m[43m [49m[43mkwargs[49m[43m)[49m[43m)[49m
[32m    137[39m [38;5;28;01mif[39;00m [38;5;28mself[39m.__return_pydantic_validator__:
[32m    138[39m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m.__return_pydantic_validator__(res)

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake_esm/core.py:689[39m, in [36mesm_datastore.to_dataset_dict[39m[34m(self, xarray_open_kwargs, xarray_combine_by_coords_kwargs, preprocess, storage_options, progressbar, aggregate, skip_on_error, **kwargs)[39m
[32m    687[39m         [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m exc:
[32m    688[39m             [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m skip_on_error:
[32m--> [39m[32m689[39m                 [38;5;28;01mraise[39;00m exc
[32m    690[39m [38;5;28mself[39m.datasets = [38;5;28mself[39m._create_derived_variables(datasets, skip_on_error)
[32m    691[39m [38;5;28;01mreturn[39;00m [38;5;28mself[39m.datasets

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake_esm/core.py:685[39m, in [36mesm_datastore.to_dataset_dict[39m[34m(self, xarray_open_kwargs, xarray_combine_by_coords_kwargs, preprocess, storage_options, progressbar, aggregate, skip_on_error, **kwargs)[39m
[32m    683[39m [38;5;28;01mfor[39;00m task [38;5;129;01min[39;00m gen:
[32m    684[39m     [38;5;28;01mtry[39;00m:
[32m--> [39m[32m685[39m         key, ds = [43mtask[49m[43m.[49m[43mresult[49m[43m([49m[43m)[49m
[32m    686[39m         datasets[key] = ds
[32m    687[39m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m exc:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/concurrent/futures/_base.py:449[39m, in [36mFuture.result[39m[34m(self, timeout)[39m
[32m    447[39m     [38;5;28;01mraise[39;00m CancelledError()
[32m    448[39m [38;5;28;01melif[39;00m [38;5;28mself[39m._state == FINISHED:
[32m--> [39m[32m449[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43m__get_result[49m[43m([49m[43m)[49m
[32m    451[39m [38;5;28mself[39m._condition.wait(timeout)
[32m    453[39m [38;5;28;01mif[39;00m [38;5;28mself[39m._state [38;5;129;01min[39;00m [CANCELLED, CANCELLED_AND_NOTIFIED]:

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/concurrent/futures/_base.py:401[39m, in [36mFuture.__get_result[39m[34m(self)[39m
[32m    399[39m [38;5;28;01mif[39;00m [38;5;28mself[39m._exception:
[32m    400[39m     [38;5;28;01mtry[39;00m:
[32m--> [39m[32m401[39m         [38;5;28;01mraise[39;00m [38;5;28mself[39m._exception
[32m    402[39m     [38;5;28;01mfinally[39;00m:
[32m    403[39m         [38;5;66;03m# Break a reference cycle with the exception in self._exception[39;00m
[32m    404[39m         [38;5;28mself[39m = [38;5;28;01mNone[39;00m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/concurrent/futures/thread.py:59[39m, in [36m_WorkItem.run[39m[34m(self)[39m
[32m     56[39m     [38;5;28;01mreturn[39;00m
[32m     58[39m [38;5;28;01mtry[39;00m:
[32m---> [39m[32m59[39m     result = [38;5;28;43mself[39;49m[43m.[49m[43mfn[49m[43m([49m[43m*[49m[38;5;28;43mself[39;49m[43m.[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[38;5;28;43mself[39;49m[43m.[49m[43mkwargs[49m[43m)[49m
[32m     60[39m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m exc:
[32m     61[39m     [38;5;28mself[39m.future.set_exception(exc)

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake_esm/core.py:836[39m, in [36m_load_source[39m[34m(key, source)[39m
[32m    835[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m_load_source[39m(key, source):
[32m--> [39m[32m836[39m     [38;5;28;01mreturn[39;00m key, [43msource[49m[43m.[49m[43mto_dask[49m[43m([49m[43m)[49m

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake_esm/source.py:300[39m, in [36mESMDataSource.to_dask[39m[34m(self)[39m
[32m    298[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mto_dask[39m([38;5;28mself[39m):
[32m    299[39m [38;5;250m    [39m[33;03m"""Return xarray object (which will have chunks)"""[39;00m
[32m--> [39m[32m300[39m     [38;5;28;43mself[39;49m[43m.[49m[43m_load_metadata[49m[43m([49m[43m)[49m
[32m    301[39m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m._ds

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake/source/base.py:84[39m, in [36mDataSourceBase._load_metadata[39m[34m(self)[39m
[32m     82[39m [38;5;250m[39m[33;03m"""load metadata only if needed"""[39;00m
[32m     83[39m [38;5;28;01mif[39;00m [38;5;28mself[39m._schema [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[32m---> [39m[32m84[39m     [38;5;28mself[39m._schema = [38;5;28;43mself[39;49m[43m.[49m[43m_get_schema[49m[43m([49m[43m)[49m
[32m     85[39m     [38;5;28mself[39m.dtype = [38;5;28mself[39m._schema.dtype
[32m     86[39m     [38;5;28mself[39m.shape = [38;5;28mself[39m._schema.shape

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake_esm/source.py:220[39m, in [36mESMDataSource._get_schema[39m[34m(self)[39m
[32m    218[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m_get_schema[39m([38;5;28mself[39m) -> Schema:
[32m    219[39m     [38;5;28;01mif[39;00m [38;5;28mself[39m._ds [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[32m--> [39m[32m220[39m         [38;5;28;43mself[39;49m[43m.[49m[43m_open_dataset[49m[43m([49m[43m)[49m
[32m    221[39m         metadata: [38;5;28mdict[39m[[38;5;28mstr[39m, typing.Any] = {[33m'[39m[33mdims[39m[33m'[39m: {}, [33m'[39m[33mdata_vars[39m[33m'[39m: {}, [33m'[39m[33mcoords[39m[33m'[39m: ()}
[32m    222[39m         [38;5;28mself[39m._schema = Schema(
[32m    223[39m             datashape=[38;5;28;01mNone[39;00m,
[32m    224[39m             dtype=[38;5;28;01mNone[39;00m,
[32m   (...)[39m[32m    227[39m             extra_metadata=metadata,
[32m    228[39m         )

[36mFile [39m[32m~/micromamba/envs/osdf-cookbook/lib/python3.12/site-packages/intake_esm/source.py:292[39m, in [36mESMDataSource._open_dataset[39m[34m(self)[39m
[32m    289[39m     [38;5;28mself[39m._ds.attrs[OPTIONS[[33m'[39m[33mdataset_key[39m[33m'[39m]] = [38;5;28mself[39m.key
[32m    291[39m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m exc:
[32m--> [39m[32m292[39m     [38;5;28;01mraise[39;00m ESMDataSourceError(
[32m    293[39m         [33mf[39m[33m"""[39m[33mFailed to load dataset with key=[39m[33m'[39m[38;5;132;01m{[39;00m[38;5;28mself[39m.key[38;5;132;01m}[39;00m[33m'[39m
[32m    294[39m [33m         You can use `cat[[39m[33m'[39m[38;5;132;01m{[39;00m[38;5;28mself[39m.key[38;5;132;01m}[39;00m[33m'[39m[33m].df` to inspect the assets/files for this key.[39m
[32m    295[39m [33m         [39m[33m"""[39m
[32m    296[39m     ) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mexc[39;00m

[31mESMDataSourceError[39m: Failed to load dataset with key='ocn.ssp370.monthly.smbb'
                 You can use `cat['ocn.ssp370.monthly.smbb'].df` to inspect the assets/files for this key.
                 